on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Run Tox tests

jobs:
  tox_test:
    name: Tox test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - name: Install dependencies
        run: |
          python -m pip install install tox tox-gh-actions --upgrade pip
      - name: Test with tox
        run: tox